import React, { createContext, useContext, useState, useEffect } from 'react';

export const ALL_LANGUAGES = [
  { code: 'en', name: 'English', native: 'English' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు' },
  { code: 'mr', name: 'Marathi', native: 'मराठी' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்' },
  { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી' },
  { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', native: 'മലയാളം' },
  { code: 'pa', name: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
  { code: 'or', name: 'Odia', native: 'ଓଡ଼ିଆ' },
  { code: 'ur', name: 'Urdu', native: 'اردو' },
  { code: 'as', name: 'Assamese', native: 'অসমীয়া' },
];

export const TRANSLATIONS = {
  en: {
    // Portal labels
    citizen_portal_title: 'Citizen Safety & Early Warning',
    citizen_portal_sub: '24x7 Citizen Safety Network • Disaster Assistance',
    gov_portal_title: 'Government of India',
    mha_title: 'Ministry of Home Affairs',
    ndma_title: 'National Disaster Management Authority (NDMA)',
    restricted_badge: 'RESTRICTED OFFICIAL ACCESS • NIC VERIFIED',
    switch_to_gov: 'Official Government Portal',
    switch_to_citizen: 'Public Citizen Portal',
    select_language: 'Select Language',
    
    // Citizen Nav
    nav_home: 'Home',
    nav_community_reports: 'Community Reports',
    nav_risk_map: 'Risk Map',
    nav_citizen_login: 'Citizen Login',
    nav_profile: 'Profile',
    sos_call: 'Call 112 (National Emergency)',

    // Government Nav
    gov_home: 'Home',
    gov_about: 'About',
    gov_disasters: 'Disaster Information',
    gov_alerts: 'Live Alerts',
    gov_risk_map: 'Risk Map',
    gov_habitations: 'Habitations',
    gov_capacity: 'Capacity',
    gov_relocation: 'Relocation',
    gov_rescue_teams: 'Rescue Teams',
    gov_analytics: 'Analytics',
    gov_resources: 'Resources',
    gov_officer_login: 'Officer Login',
    gov_sign_out: 'Sign Out Officer Session',

    // Citizen Home
    citizen_hero_tag: 'Government Certified Citizen Safety Portal',
    citizen_hero_h1_1: 'Your Safety in Disasters,',
    citizen_hero_h1_2: 'Every Second, Every Step With You.',
    citizen_hero_desc: 'Aasra Citizen Safety Network connects you with immediate rescue assistance, nearest verified relief shelters, and live official weather warnings in your local district.',
    btn_report_sos: 'Report Hazard / SOS',
    btn_find_shelter: 'Find Safe Shelters Near Me',
    emergency_dial_title: 'Emergency Fast Dial',
    emergency_dial_sub: 'Direct calling enabled (Tap number to call)',
    services_title: 'Citizen Protection Services',
    services_sub: 'Immediate tools for residents, families, and neighborhood volunteers',
    card1_title: 'Community Hazard Report',
    card1_desc: 'Notice rising river levels, landslides, road blocks, or trapped families? Submit an alert with GPS coordinates and photos for district verification.',
    card1_btn: 'Submit Incident Report',
    card2_title: 'Safe Shelters & Risk Map',
    card2_desc: 'Locate government-vetted cyclone shelters, relief camps, schools, and hospitals with available beds, safe drinking water, and backup power generators.',
    card2_btn: 'View Map & Evacuation Routes',
    card3_title: 'Citizen Profile & Alerts',
    card3_desc: 'Log in with your mobile number to track the status of your submitted reports, save family emergency contacts, and receive localized SMS/WhatsApp warnings.',
    advisories_title: 'Live District Advisories & Early Warnings',
    advisories_sub: 'Synced from IMD & CWC Feeds',
    kit_title: 'Interactive 72-Hour Family Survival Kit Checklist',
    kit_sub: 'Tick items as you pack them before evacuating or during high-alert advisories.',
    kit_progress: 'Kit Preparedness',
    dos_donts_title: 'Life-Saving Guidelines: Do\'s & Don\'ts',
    dos_donts_sub: 'Standard operating procedures for citizens during active hazards',
  },
  hi: {
    // Portal labels
    citizen_portal_title: 'नागरिक सुरक्षा एवं त्वरित चेतावनी',
    citizen_portal_sub: '24x7 नागरिक सुरक्षा नेटवर्क • आपदा सहायता',
    gov_portal_title: 'भारत सरकार',
    mha_title: 'गृह मंत्रालय',
    ndma_title: 'राष्ट्रीय आपदा प्रबंधन प्राधिकरण (NDMA)',
    restricted_badge: 'प्रतिबंधित आधिकारिक पहुंच • एनआईसी सत्यापित',
    switch_to_gov: 'आधिकारिक सरकारी पोर्टल',
    switch_to_citizen: 'नागरिक सुरक्षा पोर्टल',
    select_language: 'भाषा चुनें',

    // Citizen Nav
    nav_home: 'मुख्य पृष्ठ',
    nav_community_reports: 'सामुदायिक रिपोर्ट',
    nav_risk_map: 'जोखिम मानचित्र',
    nav_citizen_login: 'नागरिक लॉगिन',
    nav_profile: 'मेरी प्रोफाइल',
    sos_call: 'कॉल 112 (राष्ट्रीय आपातकाल)',

    // Government Nav
    gov_home: 'होम',
    gov_about: 'परिचय',
    gov_disasters: 'आपदा सूचना',
    gov_alerts: 'सजीव चेतावनियां',
    gov_risk_map: 'जोखिम मानचित्र',
    gov_habitations: 'बस्तियां',
    gov_capacity: 'आश्रय क्षमता',
    gov_relocation: 'पुनर्वास',
    gov_rescue_teams: 'बचाव दल',
    gov_analytics: 'डेटा विश्लेषण',
    gov_resources: 'राहत संसाधन',
    gov_officer_login: 'अधिकारी लॉगिन',
    gov_sign_out: 'अधिकारी सत्र समाप्त करें',

    // Citizen Home
    citizen_hero_tag: 'सरकारी प्रमाणित नागरिक सुरक्षा पोर्टल',
    citizen_hero_h1_1: 'आपदा में आपकी सुरक्षा,',
    citizen_hero_h1_2: 'हर पल, हर कदम आपके साथ।',
    citizen_hero_desc: 'Aasra (आसरा) नागरिक सुरक्षा नेटवर्क आपको त्वरित बचाव सहायता, नजदीकी सत्यापित राहत आश्रयों और आपके जिले में आधिकारिक मौसम चेतावनियों से जोड़ता है।',
    btn_report_sos: 'आपदा रिपोर्ट / आपातकालीन SOS',
    btn_find_shelter: 'नजदीकी सुरक्षित आश्रय खोजें',
    emergency_dial_title: 'आपातकालीन त्वरित डायल',
    emergency_dial_sub: 'प्रत्यक्ष कॉलिंग सक्रिय (कॉल करने के लिए नंबर टैप करें)',
    services_title: 'नागरिक सुरक्षा सेवाएं',
    services_sub: 'नागरिकों, परिवारों और स्वयंसेवकों के लिए तत्काल उपयोगी साधन',
    card1_title: 'सामुदायिक आपदा रिपोर्ट',
    card1_desc: 'जलस्तर में वृद्धि, भूस्खलन, सड़क अवरोध या फंसे हुए परिवारों को देखा? जिला प्रशासन के सत्यापन हेतु जीपीएस स्थान और फोटो के साथ तत्काल सूचना भेजें।',
    card1_btn: 'घटना रिपोर्ट दर्ज करें',
    card2_title: 'सुरक्षित आश्रय एवं मानचित्र',
    card2_desc: 'उपलब्ध बिस्तर, सुरक्षित पेयजल और बैकअप जनरेटर वाले सरकार द्वारा सत्यापित चक्रवात आश्रयों, स्कूलों और राहत शिविरों का पता लगाएं।',
    card2_btn: 'नक्शा और निकासी मार्ग देखें',
    card3_title: 'नागरिक प्रोफाइल एवं चेतावनियां',
    card3_desc: 'अपनी भेजी गई रिपोर्टों की स्थिति देखने, पारिवारिक आपातकालीन संपर्क सुरक्षित करने और स्थानीय चेतावनी पाने के लिए मोबाइल नंबर से लॉगिन करें।',
    advisories_title: 'सजीव जिला चेतावनियां एवं पूर्व सूचनाएं',
    advisories_sub: 'आईएमडी और सीडब्ल्यूसी से सीधे अपडेट',
    kit_title: '72-घंटे का पारिवारिक आपातकालीन सर्वाइवल किट',
    kit_sub: 'निकासी से पहले या उच्च चेतावनी के दौरान आवश्यक वस्तुओं को पैक करते समय टिक करें।',
    kit_progress: 'किट की तैयारी',
    dos_donts_title: 'जीवन रक्षक दिशानिर्देश: क्या करें और क्या न करें',
    dos_donts_sub: 'सक्रिय आपदाओं के दौरान नागरिकों के लिए मानक सुरक्षा उपाय',
  },
  bn: {
    citizen_portal_title: 'নাগরিক সুরক্ষা ও সতর্কতা পোর্টাল',
    citizen_portal_sub: '২৪x৭ নাগরিক সুরক্ষা নেটওয়ার্ক • দুর্যোগ সহায়তা',
    gov_portal_title: 'ভারত সরকার',
    mha_title: 'স্বরাষ্ট্র মন্ত্রক',
    ndma_title: 'জাতীয় দুর্যোগ ব্যবস্থাপনা কর্তৃপক্ষ (NDMA)',
    restricted_badge: 'নিয়ন্ত্রিত সরকারি অ্যাক্সেস • এনআইসি যাচাইকৃত',
    switch_to_gov: 'অফিসিয়াল সরকারি পোর্টাল',
    switch_to_citizen: 'নাগরিক সুরক্ষা পোর্টাল',
    select_language: 'ভাষা নির্বাচন করুন',
    nav_home: 'মূলপাতা',
    nav_community_reports: 'কমিউনিটি রিপোর্ট',
    nav_risk_map: 'ঝুঁকি মানচিত্র',
    nav_citizen_login: 'নাগরিক লগইন',
    sos_call: 'কল ১১২ (জাতীয় জরুরি)',
    gov_home: 'কমান্ড হোম',
    gov_about: 'পরিচিতি',
    gov_disasters: 'দুর্যোগ তথ্য',
    gov_alerts: 'লাইভ অ্যালার্ট',
    gov_risk_map: 'ঝুঁকি মানচিত্র',
    gov_habitations: 'বসতি এলাকা',
    gov_capacity: 'আশ্রয় ধারণক্ষমতা',
    gov_relocation: 'পুনর্বাসন পরিকল্পনা',
    gov_rescue_teams: 'উদ্ধারকারী দল (NDRF)',
    gov_analytics: 'বিশ্লেষণ',
    gov_resources: 'ত্রাণ সংস্থান',
    gov_officer_login: 'অফিসার লগইন',
    citizen_hero_h1_1: 'দুর্যোগে আপনার সুরক্ষা,',
    citizen_hero_h1_2: 'প্রতি মুহূর্তে আপনার পাশে।',
    btn_report_sos: 'জরুরি বিপদ রিপোর্ট / SOS',
    btn_find_shelter: 'নিকটবর্তী নিরাপদ আশ্রয় খুঁজুন',
  },
  te: {
    citizen_portal_title: 'పౌర భద్రత మరియు ముందస్తు హెచ్చరిక',
    citizen_portal_sub: '24x7 పౌర భద్రతా నెట్‌వర్క్ • విపత్తు సహాయం',
    gov_portal_title: 'భారత ప్రభుత్వం',
    mha_title: 'హోం వ్యవహారాల మంత్రిత్వ శాఖ',
    ndma_title: 'జాతీయ విపత్తు నిర్వహణ సంస్థ (NDMA)',
    restricted_badge: 'నిర్బంధ అధికారిక ప్రాప్యత • NIC ధృవీకరించబడింది',
    switch_to_gov: 'అధికారిక ప్రభుత్వ పోర్టల్',
    switch_to_citizen: 'ప్రజా పౌర పోర్టల్',
    select_language: 'భాషను ఎంచుకోండి',
    nav_home: 'హోమ్',
    nav_community_reports: 'కమ్యూనిటీ నివేదికలు',
    nav_risk_map: 'ప్రమాద పటం',
    nav_citizen_login: 'పౌర లాగిన్',
    sos_call: 'కాల్ 112 (జాతీయ అత్యవసర)',
    gov_home: 'కమాండ్ హోమ్',
    gov_about: 'గురించి',
    gov_disasters: 'విపత్తు సమాచారం',
    gov_alerts: 'ప్రత్యక్ష హెచ్చరికలు',
    gov_risk_map: 'ప్రమాద పటం',
    gov_habitations: 'నివాస ప్రాంతాలు',
    gov_capacity: 'ఆశ్రయ సామర్థ్యం',
    gov_relocation: 'పునరావాసం',
    gov_rescue_teams: 'రెస్క్యూ బృందాలు',
    gov_analytics: 'విశ్లేషణలు',
    gov_resources: 'వనరులు',
    gov_officer_login: 'అధికారి లాగిన్',
    citizen_hero_h1_1: 'విపత్తులలో మీ భద్రత,',
    citizen_hero_h1_2: 'ప్రతి క్షణం మీతో.',
    btn_report_sos: 'ప్రమాద నివేదిక / SOS',
    btn_find_shelter: 'సురక్షిత ఆశ్రయాన్ని కనుగొనండి',
  },
  mr: {
    citizen_portal_title: 'नागरिक सुरक्षा आणि पूर्वसूचना पोर्टल',
    citizen_portal_sub: '२४x७ नागरिक सुरक्षा नेटवर्क • आपत्ती साहाय्य',
    gov_portal_title: 'भारत सरकार',
    mha_title: 'गृह मंत्रालय',
    ndma_title: 'राष्ट्रीय आपत्ती व्यवस्थापन प्राधिकरण (NDMA)',
    restricted_badge: 'प्रतिबंधित अधिकृत प्रवेश • NIC प्रमाणित',
    switch_to_gov: 'अधिकृत शासकीय पोर्टल',
    switch_to_citizen: 'नागरिक सुरक्षा पोर्टल',
    select_language: 'भाषा निवडा',
    nav_home: 'मुख्यपृष्ठ',
    nav_community_reports: 'नागरिक अहवाल',
    nav_risk_map: 'धोका नकाशा',
    nav_citizen_login: 'नागरिक लॉगिन',
    sos_call: 'कॉल ११२ (राष्ट्रीय आणीबाणी)',
    gov_home: 'कमांड होम',
    gov_about: 'परिचय',
    gov_disasters: 'आपत्ती माहिती',
    gov_alerts: 'थेट सूचना',
    gov_risk_map: 'धोका नकाशा',
    gov_habitations: 'संवेदनशील वस्त्या',
    gov_capacity: 'निवारा क्षमता',
    gov_relocation: 'पुनर्वसन योजना',
    gov_rescue_teams: 'बचाव पथके (NDRF)',
    gov_analytics: 'डेटा विश्लेषण',
    gov_resources: 'साधने व सामग्री',
    gov_officer_login: 'अधिकारी लॉगिन',
    citizen_hero_h1_1: 'आपत्तीमध्ये आपली सुरक्षा,',
    citizen_hero_h1_2: 'प्रत्येक क्षणी आपल्या सोबत.',
    btn_report_sos: 'धोका नोंदवा / आपत्कालीन SOS',
    btn_find_shelter: 'जवळचा सुरक्षित निवारा शोधा',
  },
  ta: {
    citizen_portal_title: 'குடிமக்கள் பாதுகாப்பு மற்றும் எச்சரிக்கை',
    citizen_portal_sub: '24x7 குடிமக்கள் பாதுகாப்பு நெட்வொர்க் • பேரிடர் உதவி',
    gov_portal_title: 'இந்திய அரசு',
    mha_title: 'உள்துறை அமைச்சகம்',
    ndma_title: 'தேசிய பேரிடர் மேலாண்மை ஆணையம் (NDMA)',
    restricted_badge: 'அங்கீகரிக்கப்பட்ட அணுகல் • NIC சரிபார்க்கப்பட்டது',
    switch_to_gov: 'அதிகாரப்பூர்வ அரசு தளம்',
    switch_to_citizen: 'குடிமக்கள் தளம்',
    select_language: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    nav_home: 'முகப்பு',
    nav_community_reports: 'சமூக புகார்கள்',
    nav_risk_map: 'அபாய வரைபடம்',
    nav_citizen_login: 'குடிமக்கள் உள்நுழைவு',
    sos_call: 'அழைக்கவும் 112 (அவசர உதவி)',
    gov_home: 'கட்டளை முகப்பு',
    gov_about: 'பற்றி',
    gov_disasters: 'பேரிடர் தகவல்',
    gov_alerts: 'நேரலை எச்சரிக்கைகள்',
    gov_risk_map: 'அபாய வரைபடம்',
    gov_habitations: 'குடியிருப்புகள்',
    gov_capacity: 'தங்குமிட திறன்',
    gov_relocation: 'மறுவாழ்வு திட்டம்',
    gov_rescue_teams: 'மீட்புக் குழுக்கள்',
    gov_analytics: 'பகுப்பாய்வு',
    gov_resources: 'வளங்கள்',
    gov_officer_login: 'அதிகாரி உள்நுழைவு',
    citizen_hero_h1_1: 'பேரிடரில் உங்கள் பாதுகாப்பு,',
    citizen_hero_h1_2: 'ஒவ்வொரு நொடியும் உங்களுடன்.',
    btn_report_sos: 'அபாயத்தை தெரிவிக்க / SOS',
    btn_find_shelter: 'பாதுகாப்பான தங்குமிடம்',
  },
  gu: {
    citizen_portal_title: 'નાગરિક સુરક્ષા અને પૂર્વ ચેતવણી',
    citizen_portal_sub: '24x7 નાગરિક સુરક્ષા નેટવર્ક • આપત્તિ સહાય',
    gov_portal_title: 'ભારત સરકાર',
    mha_title: 'ગૃહ મંત્રાલય',
    ndma_title: 'રાષ્ટ્રીય આપત્તિ વ્યવસ્થાપન સત્તામંડળ (NDMA)',
    restricted_badge: 'પ્રતિબંધિત સત્તાવાર પ્રવેશ • NIC માન્ય',
    switch_to_gov: 'સત્તાવાર સરકારી પોર્ટલ',
    switch_to_citizen: 'નાગરિક સુરક્ષા પોર્ટલ',
    select_language: 'ભાષા પસંદ કરો',
    nav_home: 'હોમ',
    nav_community_reports: 'સામુદાયિક અહેવાલ',
    nav_risk_map: 'જોખમ નકશો',
    nav_citizen_login: 'નાગરિક લૉગિન',
    sos_call: 'કૉલ ૧૧૨ (કટોકટી)',
    gov_home: 'કમાન્ડ હોમ',
    gov_about: 'પરિચય',
    gov_disasters: 'આપત્તિ માહિતી',
    gov_alerts: 'લાઇવ ચેતવણીઓ',
    gov_risk_map: 'જોખમ નકશો',
    gov_habitations: 'વસાહતો',
    gov_capacity: 'આશ્રય ક્ષમતા',
    gov_relocation: 'પુનર્વસન',
    gov_rescue_teams: 'બચાવ દળો (NDRF)',
    gov_analytics: 'વિશ્લેષણ',
    gov_resources: 'રાહત સંસાધનો',
    gov_officer_login: 'અધિકારી લૉગિન',
    citizen_hero_h1_1: 'આપત્તિમાં તમારી સુરક્ષા,',
    citizen_hero_h1_2: 'દરેક ક્ષણે તમારી સાથે.',
    btn_report_sos: 'જોખમ અહેવાલ / SOS',
    btn_find_shelter: 'નજીકનો આશ્રય શોધો',
  },
  kn: {
    citizen_portal_title: 'ನಾಗರಿಕ ಸುರಕ್ಷತೆ ಮತ್ತು ಮುನ್ನೆಚ್ಚರಿಕೆ',
    citizen_portal_sub: '24x7 ನಾಗರಿಕ ಸುರಕ್ಷತೆ • ವಿಪತ್ತು ನೆರವು',
    gov_portal_title: 'ಭಾರತ ಸರ್ಕಾರ',
    mha_title: 'ಗೃಹ ವ್ಯವಹಾರಗಳ ಸಚಿವಾಲಯ',
    ndma_title: 'ರಾಷ್ಟ್ರೀಯ ವಿಪತ್ತು ನಿರ್ವಹಣಾ ಪ್ರಾಧಿಕಾರ (NDMA)',
    restricted_badge: 'ಅಧಿಕೃತ ಪ್ರವೇಶ • NIC ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    switch_to_gov: 'ಅಧಿಕೃತ ಸರ್ಕಾರಿ ಪೋರ್ಟಲ್',
    switch_to_citizen: 'ನಾಗರಿಕ ಸುರಕ್ಷತಾ ಪೋರ್ಟಲ್',
    select_language: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    nav_home: 'ಮುಖಪುಟ',
    nav_community_reports: 'ಸಮುದಾಯ ವರದಿಗಳು',
    nav_risk_map: 'ಅಪಾಯ ನಕ್ಷೆ',
    nav_citizen_login: 'ನಾಗರಿಕ ಲಾಗಿನ್',
    sos_call: 'ಕರೆ 112 (ತುರ್ತು)',
    gov_home: 'ಕಮಾಂಡ್ ಹೋಮ್',
    gov_about: 'ಪರಿಚಯ',
    gov_disasters: 'ವಿಪತ್ತು ಮಾಹಿತಿ',
    gov_alerts: 'ಲೈವ್ ಎಚ್ಚರಿಕೆಗಳು',
    gov_risk_map: 'ಅಪಾಯ ನಕ್ಷೆ',
    gov_habitations: 'ವಸತಿ ಪ್ರದೇಶಗಳು',
    gov_capacity: 'ಆಶ್ರಯ ಸಾಮರ್ಥ್ಯ',
    gov_relocation: 'ಪುನರ್ವಸತಿ',
    gov_rescue_teams: 'ರಕ್ಷಣಾ ತಂಡಗಳು',
    gov_analytics: 'ವಿಶ್ಲೇಷಣೆ',
    gov_resources: 'ಸಂಪನ್ಮೂಲಗಳು',
    gov_officer_login: 'ಅಧಿಕಾರಿ ಲಾಗಿನ್',
    citizen_hero_h1_1: 'ವಿಪತ್ತಿನಲ್ಲಿ ನಿಮ್ಮ ಸುರಕ್ಷತೆ,',
    citizen_hero_h1_2: 'ಪ್ರತಿ ಕ್ಷಣವೂ ನಿಮ್ಮೊಂದಿಗೆ.',
    btn_report_sos: 'ವಿಪತ್ತು ವರದಿ / SOS',
    btn_find_shelter: 'ಸುರಕ್ಷಿತ ಆಶ್ರಯ ಹುಡುಕಿ',
  },
  ml: {
    citizen_portal_title: 'പൗര സുരക്ഷാ മുൻകരുതൽ പോർട്ടൽ',
    citizen_portal_sub: '24x7 പൗര സുരക്ഷാ ശൃംഖല • ദുരന്ത സഹായം',
    gov_portal_title: 'ഭാരത സർക്കാർ',
    mha_title: 'ആഭ്യന്തര മന്ത്രാലയം',
    ndma_title: 'ദേശീയ ദുരന്ത നിവാരണ അതോറിറ്റി (NDMA)',
    restricted_badge: 'ഔദ്യോഗിക പ്രവേശനം • NIC അംഗീകൃതം',
    switch_to_gov: 'ഔദ്യോഗിക സർക്കാർ പോർട്ടൽ',
    switch_to_citizen: 'പൗര സുരക്ഷാ പോർട്ടൽ',
    select_language: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    nav_home: 'ഹോം',
    nav_community_reports: 'കമ്മ്യൂണിറ്റി റിപ്പോർട്ടുകൾ',
    nav_risk_map: 'അപകട മാപ്പ്',
    nav_citizen_login: 'പൗര ലോഗിൻ',
    sos_call: 'വിളിക്കുക 112 (അടിയന്തിരം)',
    gov_home: 'കമാൻഡ് ഹോം',
    gov_about: 'വിവരണം',
    gov_disasters: 'ദുരന്ത വിവരങ്ങൾ',
    gov_alerts: 'തത്സമയ മുന്നറിയിപ്പുകൾ',
    gov_risk_map: 'അപകട മാപ്പ്',
    gov_habitations: 'വാസസ്ഥലങ്ങൾ',
    gov_capacity: 'ആശ്രയ ശേഷി',
    gov_relocation: 'പുനരധിവാസം',
    gov_rescue_teams: 'രക്ഷാപ്രവർത്തകർ (NDRF)',
    gov_analytics: 'വിശകലനം',
    gov_resources: 'വിഭവങ്ങൾ',
    gov_officer_login: 'ഓഫീസർ ലോഗിൻ',
    citizen_hero_h1_1: 'ദുരന്തങ്ങളിൽ നിങ്ങളുടെ സുരക്ഷ,',
    citizen_hero_h1_2: 'ഓരോ നിമിഷവും നിങ്ങളുടെ കൂടെ.',
    btn_report_sos: 'അപകട റിപ്പോർട്ട് / SOS',
    btn_find_shelter: 'സുരക്ഷിത അഭയകേന്ദ്രം കണ്ടെത്തുക',
  },
  pa: {
    citizen_portal_title: 'ਨਾਗਰਿਕ ਸੁਰੱਖਿਆ ਅਤੇ ਚੇਤਾਵਨੀ ਪੋਰਟਲ',
    citizen_portal_sub: '24x7 ਨਾਗਰਿਕ ਸੁਰੱਖਿਆ • ਆਫ਼ਤ ਸਹਾਇਤਾ',
    gov_portal_title: 'ਭਾਰਤ ਸਰਕਾਰ',
    mha_title: 'ਗ੍ਰਹਿ ਮੰਤਰਾਲਾ',
    ndma_title: 'ਰਾਸ਼ਟਰੀ ਆਫ਼ਤ ਪ੍ਰਬੰਧਨ ਅਥਾਰਟੀ (NDMA)',
    restricted_badge: 'ਸਰਕਾਰੀ ਪਹੁੰਚ • NIC ਪ੍ਰਮਾਣਿਤ',
    switch_to_gov: 'ਸਰਕਾਰੀ ਪੋਰਟਲ',
    switch_to_citizen: 'ਨਾਗਰਿਕ ਪੋਰਟਲ',
    select_language: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    nav_home: 'ਮੁੱਖ ਪੰਨਾ',
    nav_community_reports: 'ਕਮਿਊਨਿਟੀ ਰਿਪੋਰਟਾਂ',
    nav_risk_map: 'ਜੋਖਮ ਨਕਸ਼ਾ',
    nav_citizen_login: 'ਨਾਗਰਿਕ ਲੌਗਇਨ',
    sos_call: 'ਕਾਲ 112 (ਐਮਰਜੈਂਸੀ)',
    gov_home: 'ਕਮਾਂਡ ਹੋਮ',
    gov_about: 'ਜਾਣ-ਪਛਾਣ',
    gov_disasters: 'ਆਫ਼ਤ ਜਾਣਕਾਰੀ',
    gov_alerts: 'ਲਾਈਵ ਅਲਰਟ',
    gov_risk_map: 'ਜੋਖਮ ਨਕਸ਼ਾ',
    gov_habitations: 'ਵੱਸੋਂ ਵਾਲੇ ਖੇਤਰ',
    gov_capacity: 'ਸ਼ਰਨ ਸਮਰੱਥਾ',
    gov_relocation: 'ਪੁਨਰਵਾਸ ਯੋਜਨਾ',
    gov_rescue_teams: 'ਬਚਾਅ ਟੀਮਾਂ',
    gov_analytics: 'ਵਿਸ਼ਲੇਸ਼ਣ',
    gov_resources: 'ਰਾਹਤ ਸਰੋਤ',
    gov_officer_login: 'ਅਧਿਕਾਰੀ ਲੌਗਇਨ',
    citizen_hero_h1_1: 'ਆਫ਼ਤ ਵਿੱਚ ਤੁਹਾਡੀ ਸੁਰੱਖਿਆ,',
    citizen_hero_h1_2: 'ਹਰ ਪਲ ਤੁਹਾਡੇ ਨਾਲ।',
    btn_report_sos: 'ਖ਼ਤਰਾ ਰਿਪੋਰਟ / SOS',
    btn_find_shelter: 'ਸੁਰੱਖਿਅਤ ਸ਼ਰਨ ਲੱਭੋ',
  },
  or: {
    citizen_portal_title: 'ନାଗରିକ ସୁରକ୍ଷା ଓ ସତର୍କତା ପୋର୍ଟାଲ',
    citizen_portal_sub: '୨୪x୭ ନାଗରିକ ସୁରକ୍ଷା • ବିପର୍ଯ୍ୟୟ ସହାୟତା',
    gov_portal_title: 'ଭାରତ ସରକାର',
    mha_title: 'ଗୃହ ମନ୍ତ୍ରଣାଳୟ',
    ndma_title: 'ଜାତୀୟ ବିପର୍ଯ୍ୟୟ ପରିଚାଳନା ପ୍ରାଧିକରଣ (NDMA)',
    restricted_badge: 'ସରକାରୀ ପ୍ରବେଶ • NIC ପ୍ରମାଣିତ',
    switch_to_gov: 'ସରକାରୀ ପୋର୍ଟାଲ',
    switch_to_citizen: 'ନାଗରିକ ପୋର୍ଟାଲ',
    select_language: 'ଭାଷା ବାଛନ୍ତୁ',
    nav_home: 'ମୂଳପୃଷ୍ଠା',
    nav_community_reports: 'ସମୁଦାୟ ରିପୋର୍ଟ',
    nav_risk_map: 'ବିପଦ ମାନଚିତ୍ର',
    nav_citizen_login: 'ନାଗରିକ ଲଗଇନ୍',
    sos_call: 'କଲ୍ ୧୧୨ (ଜରୁରୀକାଳୀନ)',
    gov_home: 'କମାଣ୍ଡ ହୋମ୍',
    gov_about: 'ବିବରଣୀ',
    gov_disasters: 'ବିପର୍ଯ୍ୟୟ ସୂଚନା',
    gov_alerts: 'ଲାଇଭ୍ ସତର୍କତା',
    gov_risk_map: 'ବିପଦ ମାନଚିତ୍ର',
    gov_habitations: 'ବସତି ଅଞ୍ଚଳ',
    gov_capacity: 'ଆଶ୍ରୟ କ୍ଷମତା',
    gov_relocation: 'ଥଇଥାନ ଯୋଜନା',
    gov_rescue_teams: 'ଉଦ୍ଧାରକାରୀ ଦଳ',
    gov_analytics: 'ବିଶ୍ଳେଷଣ',
    gov_resources: 'ସମ୍ବଳ',
    gov_officer_login: 'ଅଧିକାରୀ ଲଗଇନ୍',
    citizen_hero_h1_1: 'ବିପର୍ଯ୍ୟୟରେ ଆପଣଙ୍କ ସୁରକ୍ଷା,',
    citizen_hero_h1_2: 'ପ୍ରତି ମୁହୂର୍ତ୍ତରେ ଆପଣଙ୍କ ସହ।',
    btn_report_sos: 'ବିପଦ ରିପୋର୍ଟ / SOS',
    btn_find_shelter: 'ନିକଟବର୍ତ୍ତୀ ଆଶ୍ରୟସ୍ଥଳୀ ଖୋଜନ୍ତୁ',
  },
  ur: {
    citizen_portal_title: 'شہری تحفظ اور قبل از وقت انتباہ',
    citizen_portal_sub: '24x7 شہری تحفظ نیٹ ورک • آفات میں امداد',
    gov_portal_title: 'حکومت ہند',
    mha_title: 'وزارت داخلہ',
    ndma_title: 'قومی ڈیزاسٹر مینجمنٹ اتھارٹی (NDMA)',
    restricted_badge: 'محدود سرکاری رسائی • این آئی سی تصدیق شدہ',
    switch_to_gov: 'سرکاری پورٹل',
    switch_to_citizen: 'عوامی شہری پورٹل',
    select_language: 'زبان منتخب کریں',
    nav_home: 'ہوم',
    nav_community_reports: 'عوامی رپورٹس',
    nav_risk_map: 'خطرہ کا نقشہ',
    nav_citizen_login: 'شہری لاگ ان',
    sos_call: 'کال کریں 112 (ہنگامی)',
    gov_home: 'کمانڈ ہوم',
    gov_about: 'تعارف',
    gov_disasters: 'آفات کی معلومات',
    gov_alerts: 'براہ راست انتباہات',
    gov_risk_map: 'نقشہ',
    gov_habitations: 'آبادیاں',
    gov_capacity: 'پناہ گاہ کی گنجائش',
    gov_relocation: 'منتقلی کا منصوبہ',
    gov_rescue_teams: 'امدادی ٹیمیں',
    gov_analytics: 'تجزیات',
    gov_resources: 'وسائل',
    gov_officer_login: 'افسر لاگ ان',
    citizen_hero_h1_1: 'آفات میں آپ کا تحفظ،',
    citizen_hero_h1_2: 'ہر لمحہ آپ کے ساتھ۔',
    btn_report_sos: 'خطرے کی رپورٹ / SOS',
    btn_find_shelter: 'محفوظ پناہ گاہ تلاش کریں',
  },
  as: {
    citizen_portal_title: 'নাগৰিক সুৰক্ষা আৰু সতৰ্কবাৰ্তা',
    citizen_portal_sub: '২৪x৭ নাগৰিক সুৰক্ষা নেটৱৰ্ক • দুৰ্যোগ সাহায্য',
    gov_portal_title: 'ভাৰত চৰকাৰ',
    mha_title: 'গৃহ মন্ত্ৰালয়',
    ndma_title: 'ৰাষ্ট্ৰীয় দুৰ্যোগ ব্যৱস্থাপনা প্ৰাধিকৰণ (NDMA)',
    restricted_badge: 'নিয়ন্ত্ৰিত চৰকাৰী প্ৰৱেশ • এনআইচি প্ৰমাণিত',
    switch_to_gov: 'চৰকাৰী পৰ্টেল',
    switch_to_citizen: 'নাগৰিক পৰ্টেল',
    select_language: 'ভাষা বাছনি কৰক',
    nav_home: 'মূলপৃষ্ঠা',
    nav_community_reports: 'ৰাইজৰ প্ৰতিবেদন',
    nav_risk_map: 'বিপদ মানচিত্ৰ',
    nav_citizen_login: 'নাগৰিক প্ৰৱেশ',
    sos_call: 'কল কৰক ১১২ (জৰুৰীকালীন)',
    gov_home: 'কমাণ্ড হোম',
    gov_about: 'পৰিচয়',
    gov_disasters: 'দুৰ্যোগ তথ্য',
    gov_alerts: 'লাইভ সতৰ্কতা',
    gov_risk_map: 'বিপদ মানচিত্ৰ',
    gov_habitations: 'বসতি অঞ্চল',
    gov_capacity: 'আশ্ৰয় ক্ষমতা',
    gov_relocation: 'পুনৰ্বাসন',
    gov_rescue_teams: 'উদ্ধাৰকাৰী দল',
    gov_analytics: 'বিশ্লেষণ',
    gov_resources: 'সম্পদসমূহ',
    gov_officer_login: 'বিষয়াৰ প্ৰৱেশ',
    citizen_hero_h1_1: 'দুৰ্যোগত আপোনাৰ সুৰক্ষা,',
    citizen_hero_h1_2: 'প্ৰতি পল আপোনাৰ লগত।',
    btn_report_sos: 'বিপদৰ খবৰ দিয়ক / SOS',
    btn_find_shelter: 'সুৰক্ষিত আশ্ৰয় বিচাৰক',
  }
};

const LanguageContext = createContext({
  language: 'en',
  setLanguage: () => {},
  allLanguages: ALL_LANGUAGES,
  t: (key) => key
});

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('aasra_language') || localStorage.getItem('diastra_language') || 'en';
  });

  const setLanguage = (langCode) => {
    setLanguageState(langCode);
    localStorage.setItem('aasra_language', langCode);
    window.dispatchEvent(new CustomEvent('languageChanged', { detail: langCode }));
  };

  useEffect(() => {
    const handleLangEvent = (e) => {
      if (e.detail && ALL_LANGUAGES.some(l => l.code === e.detail)) {
        setLanguageState(e.detail);
      }
    };
    window.addEventListener('languageChanged', handleLangEvent);
    return () => window.removeEventListener('languageChanged', handleLangEvent);
  }, []);

  const t = (key) => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, allLanguages: ALL_LANGUAGES, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
